### ISSUE TITLE
Need to make model validation to work outside AR

### ISSUE THREAD

**Issue by apaganobeleno** [wawandco/grape-tokeeo#13]
I'm thinking that this needs to implement adapter pattern for different ORM's (most common) or maybe there is a gem that handle this, the idea is to abstract model validation logic from the token comparison logic itself.

@larrymjordan any idea ?

**Comment by larrymjordan** [comment]
@apaganobeleno  Take a look at orm-adapter-support branch, is not finished yet, because we need to add specs for MongoDB, DataMapper and MongoId models, but for ActiveRecord works great.

**Comment by larrymjordan** [comment]
@apaganobeleno  guess this feature is ready to merge. 
Also i want to propose work in a new feature which allow mix token validation, for example something like:

```ruby
ensure_token in: User, field: :token do |token, model |
  model.role == 'ADMIN'
end
```

This piece of code allow to check if the token exist in a repository but also if token's owner is has an admin role.
